### ISSUE TITLE
code and tags for version 1.1.0 / 1.1.1

### ISSUE THREAD

**Issue by rocket-turtle** [delano/uri-redis#6]
Hello @delano

there is a version 1.1.0 / 1.1.1 on rubygems but I can not find corosponding code on github.

https://rubygems.org/gems/uri-redis
- 1.1.1 - April 05, 2024 (9 KB)
- 1.1.0 - April 05, 2024 (9 KB)
- 1.0.0 - January 17, 2023 (8,5 KB)

The gems seems legit - https://my.diffend.io/gems/uri-redis/1.0.0/1.1.1

**Comment by delano** [comment]
Hey @rocket-turtle, great catch. Thanks for creating a ticket. 

I've pushed and tagged [release v1.1.0](https://github.com/delano/uri-redis/releases/tag/v1.1.0). There was a regression in the v1.1.1 gem and it had a stale Gemfile.lock, so I've yanked it and replacing it with v1.1.2 shortly. 🙏
